apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- volumes/persistentvolumeclaim.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/configmap.yaml
- manifests/route.yaml
- manifests/gateway.yaml
images:
- name: placeholder/log-reader
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/log-reader
  newTag: main-f271fffea396ea88153a3593d091eac21a7b8d16
- name: placeholder/log-writer
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/log-writer
  newTag: main-f271fffea396ea88153a3593d091eac21a7b8d16
