name: Build and Push Images

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  IMAGE_DIR1: log-writer
  IMAGE_DIR2: log-reader
  BRANCH: ${{ github.ref_name }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: log-output-env

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud --quiet auth configure-docker $REGISTRY

      - name: Build and Push log-writer
        run: |
          IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_DIR1:$BRANCH-$GITHUB_SHA
          docker build -t $IMAGE_TAG log-output/log-writer/
          docker push $IMAGE_TAG

      - name: Build and Push log-reader
        run: |
          IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_DIR2:$BRANCH-$GITHUB_SHA
          docker build -t $IMAGE_TAG log-output/log-reader/
          docker push $IMAGE_TAG

