name: Build and Push Log output

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  IMAGE_DIR1: log-writer
  IMAGE_DIR2: log-reader
  BRANCH: ${{ github.ref_name }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: log-output-env

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud --quiet auth configure-docker $REGISTRY

      - name: Set image tags
        run: |
          echo "IMAGE_TAG1=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_DIR1:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG2=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_DIR2:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and Push log-writer
        run: |
          docker build -t $IMAGE_TAG1 log-output/log-writer/
          docker push $IMAGE_TAG1

      - name: Build and Push log-reader
        run: |
          docker build -t $IMAGE_TAG2 log-output/log-reader/
          docker push $IMAGE_TAG2

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |
          cd ./log-output
          kustomize edit set image placeholder/log-writer=$IMAGE_TAG1
          kustomize edit set image placeholder/log-reader=$IMAGE_TAG2\

      - name: Print CWD
        run: pwd

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}

